language: objective-c
osx_image: xcode10
before_script:
    - bundle install
script:
    # Test on a 1x screen.
    - xcodebuild -project Relativity.xcodeproj -scheme Relativity -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPad 2" -configuration Debug -PBXBuildsContinueAfterErrors=0 build test
    # Test on a 2x screen.
    - xcodebuild -project Relativity.xcodeproj -scheme Relativity -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 7" -configuration Debug -PBXBuildsContinueAfterErrors=0 build test
    # Test on a 3x screen.
    - xcodebuild -project Relativity.xcodeproj -scheme Relativity -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 7 Plus" -configuration Debug -PBXBuildsContinueAfterErrors=0 build test
    - pod lib lint --verbose --fail-fast
